<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CO-IT005951" name="com.automation.training.AnnotationTest" tests="5" failures="0" timestamp="11 abr 2020 00:08:52 GMT" time="0.013" errors="1">
  <testcase name="testConcact" time="0.009" classname="com.automation.training.AnnotationTest"/>
  <testcase name="testConcatenar" time="0.000" classname="com.automation.training.AnnotationTest">
    <error type="org.testng.TestNGException" message="
Parameter &#039;stringA&#039; is required by @Test on method testConcatenar but has not been marked @Optional or defined
in C:\Users\wilson.angel\AppData\Local\Temp\testng-eclipse-679067526\testng-customsuite.xml">
      <![CDATA[org.testng.TestNGException: 
Parameter 'stringA' is required by @Test on method testConcatenar but has not been marked @Optional or defined
in C:\Users\wilson.angel\AppData\Local\Temp\testng-eclipse-679067526\testng-customsuite.xml
at org.testng.internal.Parameters.createParams(Parameters.java:290)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:359)
at org.testng.internal.Parameters.createParameters(Parameters.java:620)
at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- testConcatenar -->
  <testcase name="testConcact2" time="0.002" classname="com.automation.training.AnnotationTest"/>
  <testcase name="testCount" time="0.001" classname="com.automation.training.AnnotationTest"/>
  <testcase name="testCount2" time="0.001" classname="com.automation.training.AnnotationTest"/>
</testsuite> <!-- com.automation.training.AnnotationTest -->
